AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - 'test/**/*'
    - 'examples/**/*'

Metrics/AbcSize:
  Max: 40

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 200

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
